name: Build Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: "34.0.0"

      - name: Install Cordova
        run: npm install -g cordova@12

      - name: Add Android platform
        run: cordova platform add android@12

      - name: Build Release APK
        run: cordova build android --release -- --packageType=apk

      - name: Build Release AAB
        run: cordova build android --release -- --packageType=bundle

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-builds
          path: |
            platforms/android/app/build/outputs/apk/release/*.apk
            platforms/android/app/build/outputs/bundle/release/*.aab
